### ISSUE TITLE
Question on Avalonia Template's Data Binding

### ISSUE THREAD

**Issue by realybin** [Keboo/DotnetTemplates#221]
### _Figure 1_
https://github.com/Keboo/DotnetTemplates/blob/a868177261f47be4ce6c6c359b53c066093f0661/templates/Avalonia/AvaloniaSolution/SampleAvaloniaApplication/Views/MainView.axaml.cs#L14-L18

### I felt confused on whether this line in _Figure 1_ is the best practice? Since I got in touch with Avalonia UI, I haven't learned whether I need to add this in Code Behind (_Figure 2, 3_).

**Comment by Keboo** [comment]
Hi @realybin 

Great questions.
First take a look at [this video](https://www.youtube.com/watch?v=bCryIp9HqIM) that I made a while back on the MVVM pattern and Avalonia. It will give a good foundation for understanding some of the things in this template.

For that overloaded constructor in the code behind, what is happening is that this template aims to never directly call the constructor, instead it relies on [dependency injection](https://www.youtube.com/@Kitokeboo/search?query=dependency%20injection) to automatically create the view instance as well as the corresponding view model instance. We can't delete the default constructor because that is what the designer needs to display when using the [Live Previewer](https://docs.avaloniaui.net/docs/guides/implementation-guides/ide-support). The dependency injection framework will always default to the constructor that has the most parameters, so this template leverages that behavior. 

This type of setup is only needed if you are using dependency injection within your app. For your app that you linked it doesn't appear that you are using any dependency injection so this pattern is likely not needed in your case.

**Comment by realybin** [comment]
Thanks a lot! I get it.
